[[constraint]]
  name = "github.com/bwmarrin/discordgo"
  version = "0.17.0"

[[constraint]]
  branch = "master"
  name = "github.com/justinian/dice"

[[constraint]]
  name = "github.com/kelseyhightower/envconfig"
  version = "1.3.0"
